# ----------------------------------------------------------------
# NOTE: Setting shell does not work!
# For GitHub-actions we need "bash", but
# for Windows we need "sh".
# The solution is to ensure tasks are written with bash-shebang
# if they involve bash-syntax, e.g. 'if [[ ... ]] then else fi'.
# ----------------------------------------------------------------
# set shell := [ "bash", "-c" ]

_default:
    @- just --unsorted --list

menu:
    @- just --unsorted --choose

# ----------------------------------------------------------------
# Justfile
# Recipes for various workflows.
# ----------------------------------------------------------------

set dotenv-load := true
set positional-arguments := true

# --------------------------------
# VARIABLES
# --------------------------------

PATH_ROOT := justfile_directory()
CURRENT_DIR := invocation_directory()
OS := if os_family() == "windows" { "windows" } else { "linux" }
PYVENV_ON := if os_family() == "windows" { ". .venv/Scripts/activate" } else { ". .venv/bin/activate" }
PYVENV := if os_family() == "windows" { "python" } else { "python3" }
LINTING := "ruff"
GEN_MODELS := "datamodel_code_generator"
RUST_TO_PY_BINDINGS := "maturin"
TOOL_TEST_BDD := "behave"

# --------------------------------
# Macros
# --------------------------------

_delete-file-if-exists path:
    #!/usr/bin/env bash
    if [[ -f "{{path}}" ]]; then
        rm -f {{path}}
    fi

_delete-folder-if-exists path:
    #!/usr/bin/env bash
    if [[ -d "{{path}}" ]]; then
        rm -rf {{path}}
    fi

_clean-all-files path pattern:
    #!/usr/bin/env bash
    find {{path}} -type f -name "{{pattern}}" -exec basename {} \; 2> /dev/null
    find {{path}} -type f -name "{{pattern}}" -exec rm {} \; 2> /dev/null
    exit 0;

_clean-all-folders path pattern:
    #!/usr/bin/env bash
    find {{path}} -type d -name "{{pattern}}" -exec basename {} \; 2> /dev/null
    find {{path}} -type d -name "{{pattern}}" -exec rm -rf {} \; 2> /dev/null
    exit 0;

_check-python-tool tool name:
    @just _check-tool "{{PYVENV}} -m {{tool}}" "{{name}}"

_check-python-bin tool name:
    @just _check-tool "{{tool}}" "{{name}}"

_check-tool tool name:
    #!/usr/bin/env bash
    success=false
    {{PYVENV_ON}} && {{tool}} --version >> /dev/null 2> /dev/null && success=true;
    {{PYVENV_ON}} && {{tool}} --help >> /dev/null 2> /dev/null && success=true;
    # NOTE: if exitcode is 251 (= help or print version), then render success.
    if [[ "$?" == "251" ]]; then success=true; fi
    # FAIL tool not installed
    if ( $success ); then
        echo -e "Tool \x1b[2;3m{{name}}\x1b[0m installed correctly.";
        exit 0;
    else
        echo -e "Tool \x1b[2;3m{{tool}}\x1b[0m did not work." >> /dev/stderr;
        echo -e "Ensure that \x1b[2;3m{{name}}\x1b[0m (-> \x1b[1mjust build\x1b[0m) installed correctly and system paths are set." >> /dev/stderr;
        exit 1;
    fi

_generate-models path_schema target_path name:
    @ # cf. https://github.com/koxudaxi/datamodel-code-generator?tab=readme-ov-file#all-command-options
    @{{PYVENV_ON}} && {{PYVENV}} -m {{GEN_MODELS}} \
        --input-file-type openapi \
        --output-model-type pydantic_v2.BaseModel \
        --formatters "ruff-format" \
        --encoding "UTF-8" \
        --disable-timestamp \
        --use-schema-description \
        --no-use-annotated \
        --use-standard-collections \
        --use-union-operator \
        --use-default-kwarg \
        --field-constraints \
        --output-datetime-class datetime \
        --use-specialized-enum \
        --capitalise-enum-members \
        --enum-field-as-literal none \
        --set-default-enum-member \
        --use-subclass-enum \
        --allow-population-by-field-name \
        --strict-nullable \
        --use-double-quotes \
        --use-type-alias \
        --use-field-description \
        --target-python-version 3.14 \
        --input "{{path_schema}}/schema-{{name}}.yaml" \
        --output "{{target_path}}/{{name}}.py"

_generate-models-recursively path_schema target_path:
    #!/usr/bin/env bash
    while read path; do
        if [[ "${path}" == "" ]]; then continue; fi
        path="${path##*/}";
        name="$( echo """${path}""" | sed -E """s/^schema-(.*)\.yaml$/\1/g""")";
        echo "- generate models for ${name}."
        just _generate-models "{{path_schema}}" "{{target_path}}" "${name}";
    done <<< "$( ls -f {{path_schema}}/schema-*.yaml )";
    exit 0;

# ----------------------------------------------------------------
# TARGETS
# ----------------------------------------------------------------

# --------------------------------
# TARGETS: build
# --------------------------------

[group("build")]
setup:
    @echo "TASK: SETUP"
    @cp -n "templates/template.env"  ".env"

[group("build")]
build pkg="first-party":
    @echo "TASK: BUILD"
    @- just build-venv
    @just build-requirements "{{pkg}}"
    @just check-system
    @just build-models

[group("build")]
build-venv:
    @echo "SUBTASK: create venv if not exists"
    @${PYTHON_PATH} -m venv .venv

[group("build")]
build-requirements pkg="first-party":
    @echo "SUBTASK: build requirements"
    @just build-requirements-basic
    @- just load-assets "example_package"
    @just build-requirements-dependencies "{{pkg}}"

[group("build")]
build-requirements-basic:
    @- {{PYVENV_ON}} && {{PYVENV}} -m pip install --upgrade pip 2> /dev/null
    @{{PYVENV_ON}} && pip install ruff uv
    @# need these in order to run tool scripts
    @{{PYVENV_ON}} && pip install argparse dotenv httpx pathlib

[group("build")]
build-requirements-dependencies pkg="first-party":
    @echo "BUILD PACKAGE with dev dependencies"
    @{{PYVENV_ON}} && {{PYVENV}} -m uv sync \
        --only-group "dev" \
        --only-group "base" \
        --only-group "{{pkg}}" \
        --compile-bytecode \
        --no-managed-python \
        --no-python-downloads

[group("build")]
build-models:
    @echo "SUBTASK: build data models from schemata."
    @rm -rf "src/models/generated" 2> /dev/null
    @mkdir -p "src/models/generated"
    @touch "src/models/generated/__init__.py"
    @just _generate-models-recursively "models" "src/models/generated"

# --------------------------------
# TARGETS: execution + scripts
# --------------------------------

[group("exec")]
run-examples *args:
    @{{PYVENV_ON}} && {{PYVENV}} -m src.example {{args}}

[group("screipts")]
tool-assets *args:
    @{{PYVENV_ON}} && {{PYVENV}} -m scripts.assets {{args}}

[group("screipts")]
load-assets module:
    @{{PYVENV_ON}} && {{PYVENV}} -m scripts.assets \
        --owner "${GIT_OWNER}" \
        --repo "${GIT_REPO}" \
        --tag "${GIT_TAG}" \
        --module "{{module}}" \
        -o "dist"

# --------------------------------
# TARGETS: development
# --------------------------------

# Recipe only works if local file dev exists
[group("dev")]
dev *args:
    @{{PYVENV_ON}} && {{PYVENV}} -m dev {{args}}

[group("dev")]
ping:
    @echo "$(date '+%Y-%m-%d %H:%M:%S') \$dev [DEBUG] ping success"

[group("dev")]
greet name:
    @echo "$(date '+%Y-%m-%d %H:%M:%S') \$dev [DEBUG] Hello, {{name}}!"

# --------------------------------
# TARGETS: tests
# --------------------------------

[group("tests")]
tests:
    @just tests-unit
    @just tests-behave
    @just tests-integration

[group("tests")]
test-unit path *args:
    @{{PYVENV_ON}} && pytest "{{path}}" {{args}}

[group("tests")]
test-unit-one path method:
    @just test-unit "{{path}}" -k "{{method}}"

[group("tests")]
tests-unit:
    @just test-unit "tests/unit" --cov-reset --cov="."

# lists markers for optional tests
[group("tests")]
test-unit-list-flags:
    @{{PYVENV_ON}} && pytest --markers

[group("tests")]
test-unit-optional path flags="'(azure or remote or binary)'":
    @just test-unit "{{path}}" -m "{{flags}}"

[group("tests")]
test-unit-one-optional path method flags="'(azure or remote or binary)'":
    @just test-unit "{{path}}" -k "{{method}}" -m "{{flags}}"

[group("tests")]
tests-unit-optional flags="'(azure or remote or binary)'":
    @just test-unit "tests/unit" -m "{{flags}}"

[group("tests")]
tests-behave:
    @just test-behave "tests/behave"

[group("tests")]
test-behave path:
    @{{PYVENV_ON}} && {{PYVENV}} -m {{TOOL_TEST_BDD}} \
        --color \
        --show-timings \
        --no-capture \
        --no-logcapture \
        --multiline \
        --summary \
        "{{path}}"

# --------------------------------
# TARGETS: qa
# NOTE: use for development only.
# --------------------------------

[group("qa")]
qa:
    @{{PYVENV_ON}} && coverage report -m

[group("qa")]
coverage source_path tests_path log_path="${PATH_LOGS}":
    @{{PYVENV_ON}} && pytest {{tests_path}} \
        --ignore=tests/integration \
        --cov-reset \
        --cov={{source_path}} \
        --capture=tee-sys \
        2> /dev/null

# --------------------------------
# TARGETS: prettify
# --------------------------------

[group("linting")]
lint path:
    @{{PYVENV_ON}} && {{PYVENV}} -m {{LINTING}} check \
        --respect-gitignore \
        --show-fixes \
        --no-unsafe-fixes \
        --exit-zero \
        --fix \
        "{{path}}"
    @{{PYVENV_ON}} && {{PYVENV}} -m {{LINTING}} format \
        --respect-gitignore \
        "{{path}}"

[group("linting")]
lint-dry path:
    @{{PYVENV_ON}} && {{PYVENV}} -m {{LINTING}} check \
        --respect-gitignore \
        --no-unsafe-fixes \
        --exit-zero \
        --diff \
        "{{path}}"

[group("linting")]
lint-check path:
    @{{PYVENV_ON}} && {{PYVENV}} -m {{LINTING}} check \
        --respect-gitignore \
        --no-unsafe-fixes \
        --exit-zero \
        --verbose \
        "{{path}}"

[group("linting")]
prettify:
    @just lint "src"
    @just lint "tests"
    @just lint "scripts"

[group("linting")]
prettify-dry:
    @just lint-dry "src"
    @just lint-dry "tests"
    @just lint-dry "scripts"

# --------------------------------
# TARGETS: clean
# --------------------------------

[group("clean")]
clean log_path="${PATH_LOGS}":
    @just clean-venv
    @just clean-basic

[group("clean")]
clean-basic:
    @echo "All system artefacts will be force removed."
    @- just _clean-all-files "." ".DS_Store" 2> /dev/null
    @echo "All test artefacts will be force removed."
    @- rm -rf ".pytest_cache" 2> /dev/null
    @- rm -f ".coverage" 2> /dev/null
    @echo "All build artefacts will be force removed."
    @- rm -rf ".venv" 2> /dev/null
    @- rm -rf "build" 2> /dev/null
    @- rm -rf "bindings/rust/target" 2> /dev/null
    @- just _clean-all-folders "." ".idea" 2> /dev/null
    @- just _clean-all-folders "." "__pycache__" 2> /dev/null
    @- just _clean-all-folders "." "*.egg-info" 2> /dev/null

[group("clean")]
clean-venv:
    @echo "VENV will be removed."
    @- just _clean-all-folders "." ".venv" 2> /dev/null

# --------------------------------
# TARGETS: requirements
# --------------------------------

[group("system")]
check-system:
    @echo "Operating System detected:  {{os_family()}}"
    @echo "Python command used:        ${PYTHON_PATH}"
    @echo "Python command for venv:    {{PYVENV}}"
    @echo "Python path for venv:       $( {{PYVENV_ON}} && which {{PYVENV}} )"
