name: QA (automatic)

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
      - release
      - 'dev-*'
      - 'bugfix-*'
      - 'hotfix-*'
      - 'feat-*'
      - 'feature-*'
      - 'story-*'
    paths:
      - '**/*'
    # see <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion>
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - unlocked

permissions:
  contents: read

env:
  PYTHON_VERSION: "${{ vars.PYTHON_VERSION }}"

jobs:
  qa:
    name: QA
    runs-on: "ubuntu-latest"
    environment: "local"
    env:
      CARGO_BUILD_TARGET: "x86_64-unknown-linux-gnu"

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Action - install justfile tool
        uses: extractions/setup-just@v4
        with:
          just-version: "*"

      - name: Action - install zig
        uses: goto-bus-stop/setup-zig@v2.2.1
        with:
          version: "0.15.1"

      - name: Action - install Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Setup - add .env file
        shell: bash
        run: |-
          just setup
          touch .env
          cat <<EOF > .env
          MODULE_NAME="${{vars.MODULE_NAME}}"
          PYTHON_PATH="${{ vars.PYTHON_PATH }}"
          CARGO_BUILD_TARGET="${{ env.CARGO_BUILD_TARGET }}"
          EOF

      - name: STEP 1 - build code
        shell: bash
        run: |-
          just build

      - name:  STEP 2 - check linting
        shell: bash
        run: |-
          just prettify

      - name:  STEP 3 - run unit tests
        shell: bash
        run: |-
          just tests-unit

      - name:  STEP 4 - run behavioural tests
        shell: bash
        run: |-
          echo "Not yet implemented"
