name: Build [+ Release] (manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: |-
          Choice of environment for pipeline
        # NOTE: this option provides dropdown list of choices of environments set on GitHub (enterprise only)
        type: environment
        default: "local"

      python-version:
        description: 'Python version to use to build artefacts'
        type: choice
        options:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        default: "3.14"

      release-version:
        description: 'Release version tag'
        default: ""
        type: string

permissions:
  contents: write

env: {}

jobs:
  build:
    name: Build and release artefacts for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: "local"
    env:
      CARGO_BUILD_TARGET: "${{ matrix.architecture }}"
      TAG: '${{ github.event.inputs.release-version || github.ref_name }}'

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          # - macos-13
          - macos-14
        python-version:
          - "${{ github.event.inputs.python-version }}"
        include:
          - os: ubuntu-latest
            os-short: linux
            target: x86_64
            architecture: x86_64-unknown-linux-gnu
            python-path: "python3"

          - os: ubuntu-24.04-arm
            os-short: linux
            target: aarch64
            architecture: aarch64-unknown-linux-gnu
            python-path: "python3"

          - os: windows-latest
            os-short: win32
            target: x86_64
            architecture: x86_64-pc-windows-msvc
            # architecture: x86_64-pc-windows-gnu
            python-path: "python"

          # NOTE: no longer offered
          # - os: macos-13
          #   os-short: darwin
          #   target: x86_64
          #   architecture: x86_64-apple-darwin
          #   python-path: "python3"

          - os: macos-14
            os-short: darwin
            target: arm64
            architecture: aarch64-apple-darwin
            python-path: "python3"

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Action - install justfile tool
        uses: extractions/setup-just@v4
        with:
          just-version: "*"

      - name: Action - install zig
        if: ${{ matrix.os-short != 'win32' }}
        uses: goto-bus-stop/setup-zig@v2.2.1
        with:
          version: "0.15.1"

      - name: Action - install Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Action - install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.16.0
        with:
          target: ${{ matrix.architecture }}

      - name: Setup - add .env file
        shell: bash
        run: |-
          just setup
          cat <<EOF >> .env
          MODULE_NAME="${{ vars.MODULE_NAME }}"
          PYTHON_PATH="${{ matrix.python-path }}"
          CARGO_BUILD_TARGET="${{ matrix.architecture }}"
          EOF

      - name: STEP 1 - Create pre-built artefacts ("wheels")
        shell: bash
        run: |-
          just build-py

      - name: STEP 2 - Upload to GitHub Releases
        if: ${{ env.TAG != '' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: '${{ env.TAG }}'
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
