name: Build [+ Release] (manual)

on:
  push:
    tags:
      - 'v*'  # trigger on creation of tags vX.Y.Z

  workflow_dispatch:
    inputs:
      environment:
        description: |-
          Choice of environment for pipeline
        # NOTE: this option provides dropdown list of choices of environments set on GitHub (enterprise only)
        type: environment
        default: "local"

      release-version:
        description: 'Release version tag'
        default: ""
        type: string

permissions:
  contents: write

env:
  PYTHON_VERSION: "${{ vars.PYTHON_VERSION }}"

jobs:
  build:
    name: Build artefacts for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CARGO_BUILD_TARGET: "${{ matrix.architecture }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os-short: linux
            target: x86_64
            architecture: x86_64-unknown-linux-gnu

          - os: ubuntu-24.04-arm
            os-short: linux
            target: aarch64
            architecture: aarch64-unknown-linux-gnu

          - os: windows-latest
            os-short: win32
            target: x86_64
            # architecture: x86_64-pc-windows-msvc
            architecture: x86_64-pc-windows-gnu

          # NOTE: no longer offered
          # - os: macos-13
          #   os-short: darwin
          #   target: x86_64
          #   architecture: x86_64-apple-darwin

          - os: macos-14
            os-short: darwin
            target: arm64
            architecture: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Action - install justfile tool
        uses: extractions/setup-just@v4
        with:
          just-version: "*"

      - name: Action - install zig
        if: ${{ matrix.os-short != 'win32' }}
        uses: goto-bus-stop/setup-zig@v2.2.1
        with:
          version: "0.15.1"

      - name: Action - install Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Action - install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.16.0
        with:
          target: ${{ matrix.architecture }}

      - name: Setup - add .env file
        shell: bash
        run: |-
          just setup
          cat <<EOF >> .env
          MODULE_NAME="${{ vars.MODULE_NAME }}"
          PYTHON_PATH="${{ vars.PYTHON_PATH }}"
          CARGO_BUILD_TARGET="${{ matrix.architecture }}"
          EOF

      - name: STEP 1 - Create pre-built artefacts ("wheels")
        shell: bash
        run: |-
          just build-py

      - name: STEP 2 - Buffer artefacts between job stages
        uses: actions/upload-artifact@v7.0.1
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.target }}
          path: dist/*.whl

  release:
    name: Release artefacts
    if: ${{ startsWith(github.ref, 'refs/tags/') && (github.event.inputs.release-version || github.ref_name) != '' }}
    needs: [build]
    runs-on: "ubuntu-latest"
    environment: "${{ github.event.inputs.environment }}"
    env:
      TAG: '${{ github.event.inputs.release-version || github.ref_name }}'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v3
        with:
          tag_name: '${{ env.TAG }}'
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
